### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: AI 리부팅 (AI Rebooting)

# Your name to show in the footer
author: James kim

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Author's home: "https://www.linkedin.com/in/jameskim525"
#  Resources:
#    - Beautiful Jekyll: "https://beautifuljekyll.com"
#    - Learn markdown: "https://www.markdowntutorial.com/"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/AI.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "younghyeok25@gmail.com"
  github: "https://github.com/james-hyeok-kim/james-hyeok-kim.github.io.git"
  linkedin: "https://www.linkedin.com/in/jameskim525"
# rss: true # remove this line if you don't want to show an RSS link at the bottom
# facebook: deanattali
# twitter: daattali
# patreon: DeanAttali
# youtube: "@daattali"
# whatsapp: 15551212
#  medium: yourname
#  reddit: yourname or r/yoursubreddit
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname
#  strava: youruserid

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: This website is a virtual proof that I'm awesome

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false
  reddit: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "My
